#!/usr/bin/env bash
# lint.sh — quick structural lint for the atlas.
#
# This is a fast heuristic check. The full lint skill is
# .agents/skills/lint-atlas/SKILL.md — this script is the mechanical
# part that can run unattended.
#
# Checks:
#   1. [NEEDS CITATION] markers
#   2. Orphan wiki pages (no inbound wikilinks)
#   3. Broken wikilinks
#   4. Source cards not listed in source-registry.yaml
#   5. Pending registry entries
#   6. Pages missing a status field
#
# Writes a report to ops/lint-reports/lint-YYYY-MM-DD.md by default,
# or to stdout with -o -.

set -euo pipefail

cd "$(dirname "$0")/.."

OUT="ops/lint-reports/lint-$(date +%Y-%m-%d).md"
if [[ "${1:-}" == "-o" && -n "${2:-}" ]]; then
  OUT="$2"
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

{
  echo "# Atlas lint report — $(date +%Y-%m-%d)"
  echo
  echo "Generated by \`tools/lint.sh\`. See the lint-atlas skill for the"
  echo "full substantive checklist."
  echo

  echo "## [NEEDS CITATION] markers"
  echo
  if rg -n "\[NEEDS CITATION\]" wiki 2>/dev/null > "$TMPDIR/needs_citation"; then
    echo '```'
    cat "$TMPDIR/needs_citation"
    echo '```'
  else
    echo "_none_"
  fi
  echo

  echo "## Pages missing a \`status\` field"
  echo
  MISSING_STATUS=0
  while IFS= read -r -d '' page; do
    if ! rg -q '^status: ' "$page"; then
      echo "- $page"
      MISSING_STATUS=$((MISSING_STATUS + 1))
    fi
  done < <(find wiki -name "*.md" -type f -print0)
  [[ $MISSING_STATUS -eq 0 ]] && echo "_none_"
  echo

  echo "## Source cards missing from source-registry.yaml"
  echo
  MISSING_REG=0
  while IFS= read -r -d '' card; do
    slug="$(basename "$card" .md)"
    if ! rg -q "id: $slug" data/source-registry.yaml 2>/dev/null; then
      echo "- $card"
      MISSING_REG=$((MISSING_REG + 1))
    fi
  done < <(find wiki/sources -name "*.md" -type f -print0 2>/dev/null || true)
  [[ $MISSING_REG -eq 0 ]] && echo "_none_"
  echo

  echo "## Pending registry entries"
  echo
  if rg -n "status: pending" data/source-registry.yaml 2>/dev/null > "$TMPDIR/pending"; then
    echo '```'
    cat "$TMPDIR/pending"
    echo '```'
  else
    echo "_none_"
  fi
  echo

  echo "## Orphan pages (no inbound wikilinks)"
  echo
  # Collect every referenced slug.
  rg -o "\[\[([^\]|#]+)" -r '$1' wiki 2>/dev/null \
    | awk -F: '{print $NF}' | sort -u > "$TMPDIR/linked"
  ORPHANS=0
  while IFS= read -r -d '' page; do
    [[ "$(basename "$page")" == "index.md" ]] && continue
    [[ "$(basename "$page")" == "overview.md" ]] && continue
    slug="$(basename "$page" .md)"
    if ! grep -qx "$slug" "$TMPDIR/linked"; then
      echo "- $page"
      ORPHANS=$((ORPHANS + 1))
    fi
  done < <(find wiki -name "*.md" -type f -print0)
  [[ $ORPHANS -eq 0 ]] && echo "_none_"
  echo

  echo "## Summary"
  echo
  echo "- Missing status: $MISSING_STATUS"
  echo "- Missing from registry: $MISSING_REG"
  echo "- Orphans: $ORPHANS"
} > "$OUT"

if [[ "$OUT" == "-" ]]; then
  cat "$OUT"
else
  echo "wrote: $OUT"
fi
